// ─────────────────────────────────────────────────────────────
// Mirrored from the CLATians website repo (Alok16012/clatinsweb):
//   src/data/batches.ts
// This is the offline fallback for the catalog. When WEBSITE_URL is
// set, syncCatalog() overwrites these rows from the live site API.
// Keep the shapes identical to the website so the sync stays lossless.
// ─────────────────────────────────────────────────────────────

// ── Rich content shapes (stored in the `details` jsonb column) ──────────────
export interface BatchPlan {
  name: string;
  price: string;
  features: string[];
}

export interface BatchStrategySection {
  title: string;
  subtitle?: string;
  items: string[];
}

export interface BatchFeatureCard {
  title: string;
  subtitle: string;
}

export interface BatchFaq {
  question: string;
  answer: string;
}

export interface BatchReview {
  name: string;
  badge: string;   // e.g. "AIR 34" — shown as "AIR 34 · CLAT"
  text: string;
}

export interface BatchDetails {
  plans?: BatchPlan[];
  aboutDuration?: string;
  aboutStrategy?: string;
  aboutFeaturesLabel?: string;
  aboutFeatures?: BatchFeatureCard[];
  strategySections?: BatchStrategySection[];
  moreDetails?: string[];
  faqs?: BatchFaq[];
  reviews?: BatchReview[];
}

export interface Batch {
  slug: string;
  courseSlug: string;
  category: string;
  name: string;
  exam: string;
  batchCode: string;
  startDate: string;
  endDate: string;
  duration: string;
  schedule: string;
  mode: string;
  seats: number;
  filled: number;
  fee: string;
  originalFee?: string;
  emi: string;
  offer?: string;
  color: string;
  bg: string;
  status: 'upcoming' | 'ongoing' | 'filling-fast';
  language: 'Hinglish' | 'English' | 'Bilingual';
  batchType: string;
  chips: string[];
  faculty: string[];
  highlights: string[];
  syllabus: string[];
  description: string;
  details?: BatchDetails;
}

export const batches: Batch[] = [
  // ── OFFLINE BATCHES ─────────────────────────────────────────
  {
    slug: 'clat-2027-foundation',
    courseSlug: 'clat',
    category: 'offline',
    name: 'Foundation Batch for CLAT-2028',
    exam: 'CLAT',
    batchCode: 'OFF-CLAT-F28',
    startDate: 'May, 2026',
    endDate: 'Till CLAT 2028',
    duration: '30 Months (Till Nov 2027)',
    schedule: 'Mon – Sat · Morning Batch',
    mode: 'Offline (Patna Center)',
    seats: 30,
    filled: 13,
    fee: '₹1,55,000',
    originalFee: '₹1,80,000',
    emi: '₹10,500/month',
    offer: 'Upto 100% Scholarship',
    color: '#08BD80',
    bg: '#e8eeff',
    status: 'upcoming',
    language: 'Hinglish',
    batchType: 'Dream Batch',
    chips: ['Offline Classes', 'Personal Mentorship', 'Books, Notes & Magazines', 'Mock Test Series'],
    faculty: ['A.K. Singh', 'Senior Faculty Team'],
    highlights: [
      'Foundation batch for 2-year comprehensive CLAT preparation',
      'Daily classroom sessions at CLATians Patna center',
      'Complete printed study material — 8 volumes',
      '50+ full-length CLAT mock tests with analysis',
      'Personal mentorship by A.K. Singh (Director)',
      'Monthly parent-teacher meetings',
      'Library access with law books & journals',
      'Hinglish medium for better understanding',
    ],
    syllabus: [
      'English Language & Comprehension',
      'Current Affairs & GK (Daily)',
      'Legal Reasoning & Law Awareness',
      'Logical Reasoning',
      'Quantitative Techniques',
      'CLAT Mock Test Practice & Analysis',
    ],
    description: 'Our 2-year Foundation Batch for students targeting CLAT 2028. Ideal for students in Class 11 who want to build a strong foundation over 30 months.',
    details: {
      plans: [
        {
          name: 'Foundation Batch for CLAT-2028',
          price: '1,53,000',
          features: [
            'Classroom Lectures',
            'Books, Notes & DPD',
            'Monthly Magazine',
            'Sectional & Topic-wise Test',
            'Mock Test Series',
            'CLAT Question Banks',
            'Library Access',
          ],
        },
        {
          name: 'Foundation Batch for CLAT-2028 Pro Batch',
          price: '1,66,500',
          features: [
            'Classroom Lectures',
            'Online Resources Access',
            'Books, Notes & DPD',
            'Monthly Magazine',
            'Personal Mentorship',
            'Special English Batch',
            'Sectional & Topic-wise Test',
            'Mock Test Series',
            'CLAT Question Banks',
            'Library Access',
          ],
        },
      ],
      aboutDuration: 'From Admission – CLAT 2028 Exam',
      aboutStrategy: 'Basic Syllabus → Advance Syllabus → Mock Test Series',
      aboutFeaturesLabel: 'Online Resources Access',
      aboutFeatures: [
        { title: 'Monthly Magazine', subtitle: 'Current Affairs & Legal Affairs' },
        { title: 'Study Material', subtitle: 'Comprehensive study materials, Books, DPDs & more' },
        { title: 'Personal Mentorship', subtitle: 'A Personal Mentor Assign for Better Preparation' },
        { title: 'Special Class', subtitle: 'Special English Batch' },
        { title: 'Doubt Resolution', subtitle: '24/7 doubt solving support (Online)' },
        { title: 'Performance Tracking', subtitle: 'Regular progress monitoring and analysis' },
      ],
      strategySections: [
        {
          title: 'Subject Covering',
          items: [],
        },
        {
          title: 'Basic Syllabus',
          items: [
            'Topic wise Classes',
            'Questions Practice Session including Solution Classes (From covered Topic)',
            'Additional Doubt Session (From covered Topic)',
            'Unit Tests (From covered Topic)',
          ],
        },
        {
          title: 'Advance Syllabus',
          items: [
            'Advance Level Question Practice Session',
            'Doubt Session',
            'Weekly Tests (i.e. Mock Test)',
          ],
        },
        {
          title: 'Mock Test Series & Revision Classes',
          subtitle: 'Till CLAT Examinations',
          items: [
            'Mock Test — Weekly, 1st 60 Days',
            'Solution Classes — 1 Subject per Day',
          ],
        },
        {
          title: 'Regular Mock Test',
          subtitle: 'After 60 Days (Till Exam)',
          items: [
            'Mock Test',
            'Solution Classes',
            'Revision Classes',
          ],
        },
      ],
      moreDetails: [
        'Comprehensive Preparation Method & Syllabus Coverage of CLAT 2027.',
        'Preparation Strategy Guide for Students: with a detailed & structured approach that will maximize your chances of success. This comprehensive plan divides your journey into three phases, each with specific goals and activities.',
        'Well Qualified & cooperative Faculties.',
        '25000+ Questions Practice with Solution.',
        'More than 200 Comprehensive Tests with Solution.',
        'Monthly Magazines (including Current Affairs & Legal Reasoning).',
        'Total 500+ Daily Practice Drills (DPDs) with detailed solutions.',
        'Small Batch: The "20 Students Batch" ensures personalized attention and focused learning. With a smaller class size, students receive better interaction with instructors, enabling tailored support in key areas. This setup enhances the quality of CLAT preparation, helping students excel and secure top NLUs.',
        'The "Personal Mentorship" feature: one-on-one guidance from expert mentors. Tailored to individual needs, this personalized support helps students enhance their strengths, address weaknesses, and stay focused on their CLAT preparation. With regular progress reviews and customized strategies, students are equipped to excel in the CLAT exam and secure top NLU admissions.',
        'Our "Performance Analysis" feature in this batch includes offline tests and detailed report cards to pinpoint weak areas. This helps students focus on improvement, enhancing skills in legal aptitude, reasoning, and general knowledge, ensuring steady progress and better chances of excelling in the CLAT exam and securing top NLU admissions.',
        'Our "Bilingual Teaching" feature ensures that classes are taught in Hinglish (Hindi & English both), making complex concepts easier to understand. This approach helps students grasp key topics more effectively, improving their CLAT preparation and boosting their chances of securing top NLUs.',
        'For any queries & concerns, please reach out to us on 8507700177.',
        'Non-Refundable Fees: Fees for study materials, tax and registration are not refundable.',
        'The registration fee is included in the price of the batch which is showing on the website. The breakup of registration fee will be mentioned on invoice. The exact details might change from one batch to another.',
        'T&C Applicable.',
      ],
      faqs: [
        {
          question: 'How does CLATians Foundation Batch differ from other CLAT coaching programs?',
          answer: 'CLATians Foundation Batch stands out with its small batch size of only 20 students, ensuring personalized attention. We offer a three-phase preparation strategy (Basic Syllabus → Advanced Syllabus → Mock Test Series), personal mentorship, bilingual teaching in Hinglish, and comprehensive performance tracking. With over 25,000 practice questions and 200+ tests, our program delivers more value than standard coaching options.',
        },
        {
          question: 'What study materials are provided in the CLATians Foundation program?',
          answer: 'Students receive comprehensive study materials including specially designed books, notes, 500+ Daily Practice Drills (DPDs) with detailed solutions, and monthly magazines covering Current Affairs and Legal Reasoning. These resources are tailored specifically for CLAT preparation.',
        },
        {
          question: 'What is the batch size policy at CLATians?',
          answer: 'We strictly maintain a "20 Students Batch" policy to ensure personalized attention and focused learning. This small batch size facilitates better interaction with instructors and allows for tailored support in key areas of difficulty.',
        },
        {
          question: 'How does CLATians help with Current Affairs preparation?',
          answer: 'We provide monthly magazines focused on Current Affairs and Legal Affairs. These resources are regularly updated to include the latest developments relevant to the CLAT exam, helping students stay informed about important national and international events.',
        },
        {
          question: 'Is CLATians suitable for students from non-English medium backgrounds?',
          answer: 'Absolutely! CLATians Foundation Batch is designed to be inclusive for all students, including those from non-English medium backgrounds. Our bilingual Hinglish teaching methodology makes complex concepts accessible to everyone. We also offer a Special English Batch in the Foundation PRO program to help students strengthen their English language skills, which is crucial for CLAT success.',
        },
        {
          question: 'How do the solution classes work after mock tests?',
          answer: 'After each mock test, we conduct detailed solution classes where faculty members explain the correct approaches to questions, common mistakes to avoid, and time-saving techniques. These classes are subject-wise (one subject per day) to ensure thorough analysis and learning. Students receive personalized feedback on their performance to identify areas of improvement.',
        },
      ],
    },
  },
  {
    slug: 'clat-2027-target',
    courseSlug: 'clat',
    category: 'offline',
    name: 'Target Batch for CLAT 2027',
    exam: 'CLAT',
    batchCode: 'OFF-CLAT-T27',
    startDate: 'May, 2026',
    endDate: 'Till CLAT 2027',
    duration: '12 Months (Till Dec 2026)',
    schedule: 'Mon – Sat · Morning & Evening options',
    mode: 'Offline (Patna Center)',
    seats: 20,
    filled: 8,
    fee: '₹1,05,000',
    originalFee: '₹1,20,000',
    emi: '₹8,000/month',
    offer: 'Upto 100% Scholarship',
    color: '#08BD80',
    bg: '#e8eeff',
    status: 'upcoming',
    language: 'Hinglish',
    batchType: 'Target Batch',
    chips: ['Offline Classes', 'Personal Mentorship', 'Target Study Resources', 'Unlimited Mock Test Series'],
    faculty: ['A.K. Singh', 'Senior Faculty Team'],
    highlights: [
      'Exclusive small batch — only 20 students',
      'Highly personalized attention from expert faculty',
      'Daily classroom sessions 6 days a week',
      'Complete CLAT 2027 syllabus coverage',
      '50+ full-length mock tests included',
      'Printed study material — 8 volumes',
      'Weekly doubt clearing sessions',
      'Parent-teacher meetings every month',
    ],
    syllabus: [
      'English Language & Comprehension',
      'Current Affairs & GK',
      'Legal Reasoning',
      'Logical Reasoning',
      'Quantitative Techniques',
      'CLAT Mock Test Series',
    ],
    description: 'Target Batch for CLAT 2027 — an exclusive small-batch program with only 20 students, offering maximum personalized attention.',
  },
  {
    slug: 'clat-2027-crash',
    courseSlug: 'clat',
    category: 'offline',
    name: 'Crash Course for CLAT 2027',
    exam: 'CLAT',
    batchCode: 'OFF-CLAT-CC27',
    startDate: 'Oct, 2026',
    endDate: 'Till CLAT 2027',
    duration: '3 Months (Intensive)',
    schedule: 'Mon – Sat · Full Day',
    mode: 'Offline (Patna Center)',
    seats: 20,
    filled: 5,
    fee: '₹35,000',
    originalFee: '₹50,000',
    emi: '₹12,000/month',
    offer: 'Last Chance, Start Early',
    color: '#f97316',
    bg: '#fff7ed',
    status: 'upcoming',
    language: 'Hinglish',
    batchType: 'Crash Course',
    chips: ['Offline Classes', 'Revision Material', 'Mock Test Series', 'Doubt Sessions'],
    faculty: ['A.K. Singh', 'Senior Faculty Team'],
    highlights: [
      'Intensive 3-month crash course for CLAT 2027',
      'Full-day sessions 6 days a week',
      'Complete syllabus revision in fast-track mode',
      '30+ full-length mock tests with analysis',
      'Expert doubt-clearing sessions daily',
      'Printed crash course material',
    ],
    syllabus: [
      'English Language & Comprehension',
      'Current Affairs & GK (Rapid Revision)',
      'Legal Reasoning',
      'Logical Reasoning',
      'Quantitative Techniques',
      'CLAT Mock Test Series',
    ],
    description: 'Intensive 3-month crash course for last-minute CLAT 2027 aspirants. Full-day sessions, complete syllabus revision, 30+ mock tests.',
  },
  {
    slug: 'clat-ailet-2026-offline',
    courseSlug: 'clat-ailet',
    category: 'offline',
    name: 'Target for CLAT & AILET 2026',
    exam: 'CLAT + AILET',
    batchCode: 'OFF-CLAT-AILET-26',
    startDate: 'May, 2026',
    endDate: 'Till CLAT 2026',
    duration: '7 Months (Till Nov 2025)',
    schedule: 'Mon – Sat · Morning Batch',
    mode: 'Offline (Patna Center)',
    seats: 20,
    filled: 15,
    fee: '₹1,00,000',
    originalFee: '₹1,25,000',
    emi: '₹14,300/month',
    offer: 'Upto 100% Scholarship',
    color: '#08BD80',
    bg: '#e8eeff',
    status: 'upcoming',
    language: 'Hinglish',
    batchType: 'Target Batch',
    chips: ['Offline Classes', 'Personal Mentorship', 'AILET Specific Prep', 'Mock Test Series'],
    faculty: ['A.K. Singh', 'Senior Faculty Team'],
    highlights: [
      'Covers both CLAT and AILET exam patterns',
      'Only 20 students — highly personalized batch',
      'NLU Delhi-specific AILET preparation included',
      'Daily classroom sessions at CLATians Patna center',
      'Hinglish medium for better understanding',
      '80+ full-length mock tests (CLAT + AILET)',
    ],
    syllabus: [
      'English Language & Comprehension',
      'Current Affairs & GK',
      'Legal Reasoning (CLAT & AILET pattern)',
      'Logical Reasoning',
      'Elementary Mathematics (AILET-specific)',
      'General Knowledge (AILET-specific)',
    ],
    description: 'Combined offline batch covering both CLAT and AILET for aspirants targeting top NLUs as well as NLU Delhi.',
  },
  {
    slug: 'olet-2026',
    courseSlug: 'olet',
    category: 'offline',
    name: 'Target OLET-2026',
    exam: 'AILET · CUET-LAW · MH-CET · LSAT · AIL-LET',
    batchCode: 'OFF-OLET-26',
    startDate: 'June, 2026',
    endDate: 'Till April 2027',
    duration: '10 Months (Till April 2026)',
    schedule: 'Mon – Sat · Morning Batch',
    mode: 'Offline (Patna Center)',
    seats: 20,
    filled: 10,
    fee: '₹95,000',
    originalFee: '₹1,10,000',
    emi: '₹9,500/month',
    offer: 'Upto 100% Scholarship',
    color: '#08BD80',
    bg: '#e8eeff',
    status: 'upcoming',
    language: 'Hinglish',
    batchType: 'Target Batch',
    chips: ['Offline Classes', 'Personal Mentorship', 'All Law Exams', 'Mock Test Series'],
    faculty: ['A.K. Singh', 'Senior Faculty Team'],
    highlights: [
      'Covers AILET, CUET-LAW, MH-CET, LSAT & AIL-LET',
      'Exam-specific preparation strategy for each law entrance',
      'NLU Delhi specific AILET preparation',
      'Complete study material for all covered exams',
    ],
    syllabus: [
      'AILET — GK, Legal Aptitude, Reasoning, Maths, English',
      'CUET-LAW — General Test, Language, Domain Subject',
      'MH-CET — Legal Aptitude, GK, Reasoning, English',
      'LSAT India — Analytical & Logical Reasoning, RC',
    ],
    description: 'Offline OLET batch covering all major law entrance exams — AILET, CUET-LAW, MH-CET Law, LSAT India, and AIL-LET.',
  },
  {
    slug: 'cuet-law-2026',
    courseSlug: 'cuet-ug',
    category: 'offline',
    name: 'Target Batch for CUET-2026',
    exam: 'CUET-LAW',
    batchCode: 'OFF-CUET-26',
    startDate: 'May, 2026',
    endDate: 'Till April 2027',
    duration: '11 Months (Till April 2026)',
    schedule: 'Mon – Sat · Morning Batch',
    mode: 'Offline (Patna Center)',
    seats: 25,
    filled: 12,
    fee: '₹76,000',
    originalFee: '₹95,000',
    emi: '₹7,000/month',
    offer: 'Upto 20% Scholarship',
    color: '#08BD80',
    bg: '#e8eeff',
    status: 'upcoming',
    language: 'Hinglish',
    batchType: 'Target Batch',
    chips: ['Offline Classes', 'Personal Mentorship', 'Study Material', 'Mock Test Series'],
    faculty: ['A.K. Singh', 'Senior Faculty Team'],
    highlights: [
      'Targeted preparation for CUET-LAW UG & PG',
      'Expert-led offline batch at CLATians Patna center',
      'Complete printed study material included',
      'Full-length CUET mock tests with analysis',
    ],
    syllabus: [
      'CUET-LAW General Test',
      'Language Proficiency (English & Hindi)',
      'Domain Subject — Legal Studies',
      'Current Affairs — National & International',
    ],
    description: 'Specialized offline coaching for CUET-LAW at CLATians Patna center. Covers unique CUET-LAW syllabus for admission to prestigious central universities.',
  },

  // ── ONLINE BATCHES ──────────────────────────────────────────
  {
    slug: 'clat-2026-online',
    courseSlug: 'clat-online',
    category: 'online',
    name: 'Target Batch for CLAT-2026',
    exam: 'CLAT',
    batchCode: 'ONL-CLAT-26',
    startDate: 'May, 2026',
    endDate: 'Till CLAT 2026',
    duration: '8 Months (Till Nov 2025)',
    schedule: 'Live classes 5 days/week + 24/7 recorded access',
    mode: 'Online (Live + Recorded)',
    seats: 100,
    filled: 70,
    fee: '₹15,000',
    originalFee: '₹25,000',
    emi: '₹2,500/month',
    offer: '40% Early Bird Discount',
    color: '#08BD80',
    bg: '#e8eeff',
    status: 'upcoming',
    language: 'Hinglish',
    batchType: 'Target Batch',
    chips: ['Live Classes', 'Recorded Lectures', 'AI Analytics', 'Mock Test Series'],
    faculty: ['A.K. Singh', 'Online Faculty Team'],
    highlights: [
      'Live interactive classes in Hinglish medium',
      'Recorded lectures available 24/7 on the app',
      'AI-driven performance analysis dashboard',
      '150+ online mock tests with detailed analytics',
      'Weekly live doubt-clearing sessions',
      'Digital study material + PDF notes',
    ],
    syllabus: [
      'English Language & Comprehension',
      'Current Affairs & GK',
      'Legal Reasoning',
      'Logical Reasoning',
      'Quantitative Techniques',
      'AI-powered Mock Test Series',
    ],
    description: 'India\'s most affordable online CLAT coaching — ₹15,000 only. Live interactive classes in Hinglish, recorded lectures, AI analytics.',
  },
  {
    slug: 'clat-ailet-2026-online',
    courseSlug: 'clat-ailet',
    category: 'online',
    name: 'Target CLAT & AILET-2026',
    exam: 'CLAT + AILET',
    batchCode: 'ONL-CLAT-AILET-26',
    startDate: 'Starting Soon',
    endDate: 'Till CLAT 2026',
    duration: '8 Months (Till Nov 2025)',
    schedule: 'Live classes 5 days/week + 24/7 recorded access',
    mode: 'Online (Live + Recorded)',
    seats: 100,
    filled: 45,
    fee: '₹15,000',
    originalFee: '₹25,000',
    emi: '₹2,500/month',
    offer: 'Upto 40% Scholarship',
    color: '#08BD80',
    bg: '#e8eeff',
    status: 'upcoming',
    language: 'Hinglish',
    batchType: 'Target Batch',
    chips: ['Live Classes', 'Recorded Lectures', 'AILET Specific', 'Mock Test Series'],
    faculty: ['A.K. Singh', 'Online Faculty Team'],
    highlights: [
      'Combined CLAT + AILET preparation in one program',
      'Covers both exam patterns comprehensively',
      'Live interactive Hinglish medium classes',
      '200+ online mock tests (CLAT + AILET)',
    ],
    syllabus: [
      'English Language & Comprehension',
      'Current Affairs & GK (CLAT + AILET)',
      'Legal Reasoning & Legal Aptitude',
      'Combined Mock Tests — CLAT & AILET Pattern',
    ],
    description: 'Online combined coaching for both CLAT and AILET 2026. Just ₹15,000 for complete coverage of both exams.',
  },
  {
    slug: 'clat-2027-online',
    courseSlug: 'clat-online',
    category: 'online',
    name: 'Foundation Batch for CLAT-2027',
    exam: 'CLAT',
    batchCode: 'ONL-CLAT-F27',
    startDate: 'June, 2026',
    endDate: 'Till CLAT 2027',
    duration: '18 Months (Till Nov 2026)',
    schedule: 'Live classes 5 days/week + 24/7 recorded access',
    mode: 'Online (Live + Recorded)',
    seats: 200,
    filled: 50,
    fee: '₹20,000',
    originalFee: '₹35,000',
    emi: '₹2,000/month',
    offer: 'Upto 50% Scholarship',
    color: '#08BD80',
    bg: '#e8eeff',
    status: 'upcoming',
    language: 'Hinglish',
    batchType: 'Foundation Batch',
    chips: ['Live Classes', 'Recorded Lectures', 'Study Material', 'Mock Test Series'],
    faculty: ['A.K. Singh', 'Online Faculty Team'],
    highlights: [
      '18-month foundation online program for CLAT 2027',
      'Live interactive classes in Hinglish medium',
      'Recorded lectures available 24/7',
      '200+ full-length mock tests included',
    ],
    syllabus: [
      'English Language & Comprehension',
      'Current Affairs & GK',
      'Legal Reasoning',
      'Quantitative Techniques',
    ],
    description: 'Comprehensive 18-month online foundation program for CLAT 2027. Live classes, recorded lectures, AI analytics.',
  },

  // ── MENTORSHIP BATCHES ───────────────────────────────────────
  {
    slug: 'mentorship-clat-starter',
    courseSlug: 'mentorship-clat',
    category: 'offline',
    name: 'Starter Plan — CLAT Mentorship',
    exam: 'CLAT',
    batchCode: 'MENT-CLAT-S',
    startDate: 'Anytime',
    endDate: '30 Days Access',
    duration: '1 Month',
    schedule: '4 sessions · flexible timing',
    mode: 'Online (WhatsApp + Video Call)',
    seats: 999,
    filled: 0,
    fee: '₹5,000',
    emi: 'One-time payment',
    offer: 'Best for Beginners',
    color: '#08BD80',
    bg: '#E6FAF4',
    status: 'ongoing',
    language: 'Hinglish',
    batchType: 'Starter Pack',
    chips: ['4 Live Sessions', 'Custom Study Plan', 'WhatsApp Support', 'Mock Review'],
    faculty: ['NLU Topper Mentor'],
    highlights: [
      'Initial assessment and goal setting',
      '4 one-on-one sessions with NLU mentor',
      'Custom 30-day study plan',
      'WhatsApp support between sessions',
      'Study material recommendations',
      'Progress tracking',
    ],
    syllabus: ['Initial Performance Assessment', 'Custom Study Schedule', 'Subject-wise Strategy', 'Mock Test Review'],
    description: 'Perfect starter pack for CLAT aspirants who want 1-on-1 guidance. Get a customized 30-day study plan and 4 personalized sessions with an NLU topper.',
  },
  {
    slug: 'mentorship-clat-pro',
    courseSlug: 'mentorship-clat',
    category: 'offline',
    name: 'Pro Plan — CLAT Mentorship',
    exam: 'CLAT',
    batchCode: 'MENT-CLAT-P',
    startDate: 'Anytime',
    endDate: '60 Days Access',
    duration: '2 Months',
    schedule: '8 sessions · flexible timing',
    mode: 'Online (WhatsApp + Video Call)',
    seats: 999,
    filled: 0,
    fee: '₹9,000',
    originalFee: '₹12,000',
    emi: 'One-time payment',
    offer: 'Most Popular',
    color: '#0D1837',
    bg: '#EDE9FE',
    status: 'ongoing',
    language: 'Hinglish',
    batchType: 'Pro Pack',
    chips: ['8 Live Sessions', 'Custom 60-day Plan', 'Daily WhatsApp', 'Interview Prep'],
    faculty: ['NLU Topper Mentor'],
    highlights: [
      'Comprehensive performance evaluation',
      '8 one-on-one sessions with NLU mentor',
      'Custom 60-day study plan',
      'Daily WhatsApp check-ins',
      'Mock test review sessions',
      'Interview preparation included',
      'Priority response within 2 hours',
    ],
    syllabus: ['Performance Evaluation', 'Custom 60-day Schedule', 'Mock Test Analysis', 'Interview & GD Prep'],
    description: 'The most popular mentorship plan. 8 sessions, daily WhatsApp support, and complete interview preparation — everything you need to crack CLAT.',
  },
  {
    slug: 'mentorship-clat-ultimate',
    courseSlug: 'mentorship-clat',
    category: 'offline',
    name: 'Ultimate Plan — CLAT Mentorship',
    exam: 'CLAT',
    batchCode: 'MENT-CLAT-U',
    startDate: 'Anytime',
    endDate: 'Till Exam Day',
    duration: 'Till Exam',
    schedule: 'Unlimited sessions · anytime',
    mode: 'Online (WhatsApp + Video Call)',
    seats: 999,
    filled: 0,
    fee: '₹15,000',
    originalFee: '₹20,000',
    emi: 'One-time payment',
    offer: 'Best Value',
    color: '#08BD80',
    bg: '#E6FAF4',
    status: 'ongoing',
    language: 'Hinglish',
    batchType: 'Ultimate Pack',
    chips: ['Unlimited Sessions', '24/7 WhatsApp', 'NLU Counselling', 'Till Exam Day'],
    faculty: ['NLU Topper Mentor'],
    highlights: [
      'Unlimited sessions till exam day',
      'Personalized daily study schedule',
      '24/7 WhatsApp mentor access',
      'Personal mock test series',
      'Interview + counselling prep',
      'College selection guidance',
      'Post-result NLU counselling support',
    ],
    syllabus: ['Full Exam Cycle Coverage', 'Daily Study Schedule', 'Unlimited Mock Reviews', 'NLU Counselling Support'],
    description: 'Full exam cycle mentorship with unlimited sessions till CLAT day. Includes 24/7 WhatsApp access, NLU counselling, and college selection guidance.',
  },
  {
    slug: 'mentorship-ailet-pro',
    courseSlug: 'mentorship-ailet',
    category: 'offline',
    name: 'AILET Pro Mentorship',
    exam: 'AILET',
    batchCode: 'MENT-AILET-P',
    startDate: 'Anytime',
    endDate: 'Till AILET Exam',
    duration: '2–3 Months',
    schedule: '6 sessions · flexible timing',
    mode: 'Online (WhatsApp + Video Call)',
    seats: 999,
    filled: 0,
    fee: '₹6,000',
    originalFee: '₹9,000',
    emi: 'One-time payment',
    offer: 'AILET Focused',
    color: '#6d28d9',
    bg: '#EDE9FE',
    status: 'ongoing',
    language: 'Hinglish',
    batchType: 'Pro Pack',
    chips: ['6 Live Sessions', 'AILET Strategy', 'GK Planning', 'NLU Delhi Focused'],
    faculty: ['AILET Cleared Mentor'],
    highlights: [
      'AILET-specific preparation strategy',
      'GK & current affairs for AILET pattern',
      'Elementary mathematics guidance',
      '6 sessions with AILET cleared mentor',
      'NLU Delhi specific interview prep',
      'Custom study plan for AILET timeline',
    ],
    syllabus: ['AILET Pattern Mastery', 'GK Strategy', 'Maths for AILET', 'Mock Test Review'],
    description: 'Focused 1-on-1 mentorship for AILET aspirants. Get expert guidance on AILET-specific sections and NLU Delhi admission strategy.',
  },
  {
    slug: 'nlu-counselling-basic',
    courseSlug: 'mentorship-nlu-counselling',
    category: 'offline',
    name: 'NLU Counselling — Basic',
    exam: 'CLAT / AILET',
    batchCode: 'COUNS-BASIC',
    startDate: 'After Result',
    endDate: 'Till Admission',
    duration: '2 Weeks',
    schedule: '2 sessions · post result',
    mode: 'Online (Video Call)',
    seats: 999,
    filled: 0,
    fee: '₹3,000',
    emi: 'One-time payment',
    offer: 'Post-Result Help',
    color: '#1d4ed8',
    bg: '#DBEAFE',
    status: 'ongoing',
    language: 'Hinglish',
    batchType: 'Starter Pack',
    chips: ['Preference Order Help', 'Cut-off Analysis', '2 Sessions', 'Document Help'],
    faculty: ['NLU Counselling Expert'],
    highlights: [
      'NLU preference order strategy',
      'Cut-off analysis and prediction',
      'Document checklist',
      '2 focused counselling sessions',
    ],
    syllabus: ['NLU Shortlisting', 'Preference Strategy', 'Document Prep', 'Round Tracking'],
    description: 'Post-CLAT result counselling to help you choose the right NLU preference order based on your score and category.',
  },
  {
    slug: 'nlu-counselling-premium',
    courseSlug: 'mentorship-nlu-counselling',
    category: 'offline',
    name: 'NLU Counselling — Premium',
    exam: 'CLAT / AILET',
    batchCode: 'COUNS-PREM',
    startDate: 'After Result',
    endDate: 'Till Final Admission',
    duration: '4 Weeks',
    schedule: '4 sessions + WhatsApp till admission',
    mode: 'Online (Video Call)',
    seats: 999,
    filled: 0,
    fee: '₹5,000',
    originalFee: '₹7,000',
    emi: 'One-time payment',
    offer: 'Till Final Allotment',
    color: '#1d4ed8',
    bg: '#DBEAFE',
    status: 'ongoing',
    language: 'Hinglish',
    batchType: 'Pro Pack',
    chips: ['4 Sessions', 'WhatsApp Support', 'All Rounds Help', 'Upgrade Strategy'],
    faculty: ['NLU Counselling Expert'],
    highlights: [
      'Complete round-wise counselling support',
      'Upgrade/freeze/withdrawal strategy',
      'WhatsApp support till final allotment',
      'Document verification help',
      '4 detailed counselling sessions',
      'Fee payment guidance',
    ],
    syllabus: ['Score Analysis', 'Preference Order', 'Round-wise Strategy', 'Final Admission Support'],
    description: 'End-to-end NLU counselling from result day to final admission. WhatsApp support through all rounds with upgrade strategy to get the best NLU possible.',
  },

  // ── MOCK TEST BATCHES ────────────────────────────────────────
  {
    slug: 'clat-mock-10',
    courseSlug: 'mock-tests',
    category: 'mock',
    name: 'CLAT Mock Test Series — 10 Mocks',
    exam: 'CLAT 2026',
    batchCode: 'MOCK-CLAT-10',
    startDate: 'Instant Access',
    endDate: '12 Months Access',
    duration: '12 Months',
    schedule: 'Self-paced anytime access',
    mode: 'Online + Offline PDF Download',
    seats: 999,
    filled: 300,
    fee: '₹2,999',
    originalFee: '₹4,999',
    emi: 'One-time payment',
    offer: 'Starter Pack',
    color: '#08BD80',
    bg: '#e8eeff',
    status: 'ongoing',
    language: 'English',
    batchType: 'Starter Pack',
    chips: ['10 Full Mocks', 'PDF Download', 'Detailed Solutions', 'Performance Report'],
    faculty: ['CLATians Test Team'],
    highlights: [
      '10 full-length CLAT mock tests (Easy level)',
      'Based on latest CLAT 2026 exam pattern',
      'Detailed solutions & explanations for every question',
      'Free performance report after every test',
    ],
    syllabus: [
      'English Language (28–32 questions per test)',
      'Current Affairs & GK (35–39 questions)',
      'Legal Reasoning (35–39 questions)',
      'Logical Reasoning (28–32 questions)',
      'Quantitative Techniques (13–17 questions)',
    ],
    description: 'Perfect starter pack for CLAT 2026 aspirants. 10 full-length mocks at Easy difficulty with PDF downloads.',
  },
  {
    slug: 'clat-mock-20',
    courseSlug: 'mock-tests',
    category: 'mock',
    name: 'CLAT Mock Test Series — 20 Mocks',
    exam: 'CLAT 2026',
    batchCode: 'MOCK-CLAT-20',
    startDate: 'Instant Access',
    endDate: '12 Months Access',
    duration: '12 Months',
    schedule: 'Self-paced anytime access',
    mode: 'Online + Offline PDF Download',
    seats: 999,
    filled: 450,
    fee: '₹4,999',
    originalFee: '₹7,999',
    emi: 'One-time payment',
    offer: 'Most Popular',
    color: '#08BD80',
    bg: '#e8eeff',
    status: 'ongoing',
    language: 'English',
    batchType: 'Pro Pack',
    chips: ['20 Full Mocks', 'PDF Download', 'Analytics Dashboard', 'Monthly GK Updates'],
    faculty: ['CLATians Test Team'],
    highlights: [
      '20 expertly designed CLAT mocks (Medium level)',
      'Monthly GK & Legal Current Affairs updates',
      'Sectional performance analytics dashboard',
      'Printable PDF format + online access',
    ],
    syllabus: [
      'English Language (28–32 questions per test)',
      'Current Affairs & GK (35–39 questions)',
      'Legal Reasoning (35–39 questions)',
      'Sectional analytics & improvement tips',
    ],
    description: 'Strengthen your CLAT strategy with 20 full-length mocks at Medium difficulty with sectional analytics.',
  },
  {
    slug: 'clat-mock-40',
    courseSlug: 'mock-tests',
    category: 'mock',
    name: 'CLAT Mock Test Series — 40 Mocks',
    exam: 'CLAT 2026',
    batchCode: 'MOCK-CLAT-40',
    startDate: 'Instant Access',
    endDate: '12 Months Access',
    duration: '12 Months',
    schedule: 'Self-paced anytime access',
    mode: 'Online + Offline PDF Download',
    seats: 999,
    filled: 600,
    fee: '₹8,999',
    originalFee: '₹14,999',
    emi: 'One-time payment',
    offer: 'Ultimate Pack',
    color: '#08BD80',
    bg: '#e8eeff',
    status: 'filling-fast',
    language: 'English',
    batchType: 'Ultimate Pack',
    chips: ['40 Full Mocks', 'AI Tracking', 'All India Ranking', 'Video Solutions'],
    faculty: ['CLATians Test Team'],
    highlights: [
      '40 full-length CLAT mocks for ultimate readiness',
      'AI-powered performance tracking dashboard',
      'All India Ranking & leaderboard comparison',
      'Access to exclusive topper strategy sessions',
    ],
    syllabus: [
      'English Language (28–32 questions per test)',
      'Current Affairs & GK (35–39 questions)',
      'Legal Reasoning (35–39 questions)',
      'AI performance tracking & rank prediction',
    ],
    description: 'Go all-in with 40 full-length CLAT mocks at Hard difficulty with AI tracking and All India Ranking.',
  },
];

export function getBatchesByCourse(courseSlug: string): Batch[] {
  return batches.filter((b) => b.courseSlug === courseSlug);
}

export function getBatch(courseSlug: string, batchSlug: string): Batch | undefined {
  return batches.find((b) => b.courseSlug === courseSlug && b.slug === batchSlug);
}
