// ─────────────────────────────────────────────────────────────
// Mirrored from the CLATians website repo (Alok16012/clatinsweb):
//   src/data/courses.ts
// This is the offline fallback for the catalog. When WEBSITE_URL is
// set, syncCatalog() overwrites these rows from the live site API.
// Keep the shapes identical to the website so the sync stays lossless.
// ─────────────────────────────────────────────────────────────

export interface Course {
  slug: string;
  title: string;
  category: string;
  icon: string;
  color: string;
  bg: string;
  tagline: string;
  overview: string;
  duration: string;
  batchSize: string;
  mode: string;
  fee: string;
  emi: string;
  features: string[];
  includes: { label: string; value: string; icon: string }[];
  curriculum: { module: string; topics: string[] }[];
  whoFor: string[];
  testimonial: { name: string; rank: string; college: string; quote: string; avatar: string };
}

export const courses: Course[] = [
  // ── 1. CLAT Coaching (Offline) ────────────────────────────────
  {
    slug: 'clat',
    title: 'CLAT Coaching',
    category: 'offline',
    icon: '🏛️',
    color: '#08BD80',
    bg: '#E6FAF4',
    tagline: 'Classroom coaching at CLATians Patna center — India\'s leading law entrance institute',
    overview: 'Are you searching for the best offline CLAT coaching institute to ace the Common Law Admission Test (CLAT)? Look no further! CLATians, India\'s leading CLAT preparation institute, offers expert-led classroom training designed for top NLU admissions. With personalized mentorship, structured study material, and real-time mock tests, our Offline CLAT Course ensures focused, interactive learning to maximize your success. Get hands-on guidance from experienced faculty and CLAT toppers, master the CLAT syllabus with in-depth coverage, and stay ahead with our exam-oriented approach.',
    duration: '12–30 Months',
    batchSize: '20–30 Students',
    mode: 'Offline (Patna Center)',
    fee: '₹95,000',
    emi: '₹8,000/month',
    features: [
      'Daily live classroom sessions 6 days a week',
      'Direct interaction with A.K. Singh & expert faculty',
      'Comprehensive printed study material included',
      'Weekly mock tests with detailed performance analysis',
      'Monthly parent-teacher meetings',
      'Dedicated doubt-clearing sessions daily',
      'Library access with law books & journals',
      'Personal attention in small batch of 20–30 students',
      'Hinglish medium for better understanding',
      'Free access to online test series',
    ],
    includes: [
      { label: 'Live Classes', value: '800+ Hours', icon: '📚' },
      { label: 'Mock Tests', value: '50+ Full Tests', icon: '📝' },
      { label: 'Study Material', value: '8 Volumes', icon: '📖' },
      { label: 'Doubt Sessions', value: 'Daily', icon: '💬' },
      { label: 'GK Updates', value: 'Weekly', icon: '📰' },
      { label: 'Faculty Access', value: '15+ Years Exp.', icon: '👨‍🏫' },
    ],
    curriculum: [
      { module: 'English Language', topics: ['Reading comprehension strategies', 'Grammar fundamentals', 'Vocabulary building', 'Speed reading techniques', 'Sentence correction'] },
      { module: 'Legal Reasoning', topics: ['Introduction to legal concepts', 'Constitutional law basics', 'Torts and contracts', 'Criminal law principles', 'Application of legal principles to passages'] },
      { module: 'Logical Reasoning', topics: ['Verbal reasoning', 'Analytical reasoning', 'Critical thinking', 'Puzzles and patterns', 'Syllogisms and deductions'] },
      { module: 'Current Affairs & GK', topics: ['Daily news coverage', 'Legal events and judgments', 'Static GK — India & World', 'International affairs', 'Monthly GK magazine'] },
    ],
    whoFor: [
      'Students who prefer structured classroom environment',
      'Students based in or near Patna, Bihar',
      'Students who want direct mentorship from A.K. Singh',
      'First-time CLAT aspirants targeting 2026 & 2027',
      'Droppers seeking focused repeat preparation',
    ],
    testimonial: {
      name: 'Aman Deep Singh',
      rank: 'AIR 23, CLAT 2024',
      college: 'NLU Delhi',
      quote: 'The offline program at CLATians gave me the structure I needed. Daily classes, mock tests, and A.K. Sir\'s mentorship kept me on track throughout the year.',
      avatar: 'AD',
    },
  },

  // ── 2. CLAT + AILET Combined (Offline) ───────────────────────
  {
    slug: 'clat-ailet',
    title: 'CLAT + AILET Combined',
    category: 'offline',
    icon: '⚖️',
    color: '#08BD80',
    bg: '#E6FAF4',
    tagline: 'Combined preparation for CLAT and AILET — crack both, secure NLU Delhi',
    overview: 'The CLAT + AILET Combined program at CLATians is specifically designed for aspirants who wish to maximize their chances by cracking both the Common Law Admission Test (CLAT) and the All India Law Entrance Test (AILET). NLU Delhi is India\'s most coveted law school, and our combined batch gives you a strategic edge across both exam patterns simultaneously. With dedicated AILET modules covering GK, Elementary Mathematics, and Legal Aptitude alongside regular CLAT preparation, you get comprehensive coverage without duplication of effort.',
    duration: '12–24 Months',
    batchSize: '20 Students',
    mode: 'Offline + Online',
    fee: '₹1,10,000',
    emi: '₹9,500/month',
    features: [
      'Covers both CLAT and AILET exam patterns comprehensively',
      'Dedicated AILET modules — GK, Maths, Legal Aptitude',
      'Only 20 students — highly personalized batch',
      'NLU Delhi specific preparation and strategy sessions',
      '80+ full-length mock tests for both CLAT and AILET',
      'Daily classroom sessions 6 days a week at Patna center',
      'Printed study material covering both exam syllabi',
      'Expert guidance from A.K. Singh (15+ years experience)',
    ],
    includes: [
      { label: 'Exams Covered', value: '2 Exams', icon: '📋' },
      { label: 'Mock Tests', value: '80+ Tests', icon: '📝' },
      { label: 'Study Material', value: 'Exam-wise', icon: '📖' },
      { label: 'Doubt Sessions', value: 'Daily', icon: '💬' },
      { label: 'Batch Size', value: '20 Students', icon: '👥' },
      { label: 'Expert Faculty', value: '15+ Years', icon: '👨‍🏫' },
    ],
    curriculum: [
      { module: 'CLAT Preparation', topics: ['English Language & Comprehension', 'Legal Reasoning fundamentals', 'Logical Reasoning & Critical Thinking', 'Current Affairs & GK coverage', 'CLAT full-length mock tests'] },
      { module: 'AILET-Specific Modules', topics: ['Elementary Mathematics for AILET', 'AILET-pattern Legal Aptitude', 'NLU Delhi GK requirements', 'AILET mock tests & analysis', 'Time management for AILET'] },
      { module: 'Common Core Subjects', topics: ['Reading Comprehension strategies', 'Vocabulary and grammar mastery', 'Analytical reasoning techniques', 'Legal awareness & judgments', 'Current affairs for both exams'] },
      { module: 'Mock Test & Strategy', topics: ['Combined CLAT + AILET test schedule', 'Comparative performance analysis', 'Exam-day strategy for both exams', 'Rank improvement sessions', 'Previous years\' papers practice'] },
    ],
    whoFor: [
      'Students targeting NLU Delhi (AILET) as their first choice',
      'Aspirants who want to maximize options across top NLUs',
      'Students willing to put in extra effort for both exams',
      'First-time aspirants targeting CLAT + AILET 2026',
      'Students who prefer small batch personal attention',
    ],
    testimonial: {
      name: 'Rohan Gupta',
      rank: 'AIR 12, AILET 2024',
      college: 'NLU Delhi',
      quote: 'The combined batch gave me the edge for both exams simultaneously.',
      avatar: 'RG',
    },
  },

  // ── 3. CUET-UG Law (Offline) ──────────────────────────────────
  {
    slug: 'cuet-ug',
    title: 'CUET-UG Law',
    category: 'offline',
    icon: '🎓',
    color: '#08BD80',
    bg: '#E6FAF4',
    tagline: 'Prepare smartly for CUET-UG Law — complete syllabus coverage and guided practice',
    overview: 'The CUET-UG Law program at CLATians is a focused and comprehensive coaching track designed for students who wish to pursue law through the Central Universities Common Entrance Test. CUET-UG opens doors to prestigious central universities and state universities across India. Our expert faculty covers the unique CUET-UG pattern including General Test, Language Proficiency, and Domain Subjects, ensuring you are fully prepared for this distinct exam format.',
    duration: '6–12 Months',
    batchSize: '25 Students',
    mode: 'Offline + Online',
    fee: '₹45,000',
    emi: '₹4,000/month',
    features: [
      'Specialized coaching for CUET-UG Law exam pattern',
      'Covers General Test, Language, and Legal Studies domain',
      'Expert faculty with in-depth CUET-UG knowledge',
      'Full-length CUET mock tests with detailed analysis',
      'Legal awareness and current affairs coverage',
      'Hinglish medium for better comprehension',
      'Printed study material tailored to CUET-UG pattern',
      'Monthly progress assessments and feedback sessions',
    ],
    includes: [
      { label: 'Live Classes', value: '400+ Hours', icon: '📚' },
      { label: 'Mock Tests', value: '30+ Full Tests', icon: '📝' },
      { label: 'Study Material', value: 'CUET-specific', icon: '📖' },
      { label: 'Doubt Sessions', value: 'Weekly', icon: '💬' },
      { label: 'GK Updates', value: 'Monthly', icon: '📰' },
      { label: 'Batch Size', value: '25 Students', icon: '👥' },
    ],
    curriculum: [
      { module: 'CUET General Test', topics: ['Current Affairs — National & International', 'Logical Reasoning basics', 'Quantitative Reasoning', 'General Mental Ability', 'Static GK and awareness'] },
      { module: 'Language Proficiency', topics: ['English comprehension strategies', 'Hindi language proficiency', 'Reading speed techniques', 'Grammar and sentence correction', 'Vocabulary for CUET'] },
      { module: 'Legal Studies Domain', topics: ['Introduction to Law and legal system', 'Constitutional law fundamentals', 'Legal terms and awareness', 'Landmark cases and judgments', 'Legal reasoning practice'] },
      { module: 'Mock Test Practice', topics: ['CUET-UG full-length mock tests', 'Section-wise practice sets', 'Time management strategies', 'Performance review sessions', 'Previous CUET papers'] },
    ],
    whoFor: [
      'Students targeting central university law programs via CUET',
      'Aspirants who want an alternative path to top law colleges',
      'Students from non-metro cities seeking quality CUET coaching',
      'Students appearing in CUET-UG alongside CLAT preparation',
      'First-time CUET-UG aspirants needing structured guidance',
    ],
    testimonial: {
      name: 'Kavya Reddy',
      rank: 'AIR 34, CLAT 2025',
      college: 'NALSAR Hyderabad',
      quote: 'CLATians CUET coaching covers everything perfectly.',
      avatar: 'KR',
    },
  },

  // ── 4. OLET Program (Offline) ────────────────────────────────
  {
    slug: 'olet',
    title: 'OLET Program',
    category: 'offline',
    icon: '🎯',
    color: '#08BD80',
    bg: '#E6FAF4',
    tagline: 'Other Law Entrance Tests — CLAT, AILET, CUET, AIL-LET comprehensive coverage',
    overview: 'At CLATians, we understand the challenges of cracking AILET, CUET-LAW, MH-CET-LAW, LSAT and AIL Entrance Exam. Our OLET (Other Law Entrance Tests) Coaching is designed to provide you with an immersive, results-driven approach to help you achieve your law school dreams. Maximize your chances of success — our expert mentors will guide you through each step of your preparation journey, ensuring that you are fully prepared to take on any challenge during your exam.',
    duration: '6–12 Months',
    batchSize: '15 Students',
    mode: 'Offline (Patna Center)',
    fee: '₹75,000',
    emi: '₹6,500/month',
    features: [
      'Covers AILET, CUET-LAW, MH-CET, LSAT, AIL-LET',
      'Dedicated faculty for each exam pattern',
      'Exam-specific study material for all law entrance tests',
      'Full-length mock tests for each exam',
      'NLU Delhi specific AILET preparation',
      'Maharashtra law college MH-CET strategy',
      'LSAT India preparation with analytical skills',
      'AIL-LET coaching for Army Institute of Law',
    ],
    includes: [
      { label: 'Exams Covered', value: '5+ Exams', icon: '📋' },
      { label: 'Mock Tests', value: '80+ Full Tests', icon: '📝' },
      { label: 'Study Material', value: 'Exam-wise', icon: '📖' },
      { label: 'Doubt Sessions', value: 'Daily', icon: '💬' },
      { label: 'Batch Size', value: '15 Students', icon: '👥' },
      { label: 'Expert Faculty', value: '15+ Years', icon: '👨‍🏫' },
    ],
    curriculum: [
      { module: 'AILET Preparation', topics: ['GK & Current Affairs', 'Legal Aptitude', 'Reasoning', 'Elementary Mathematics', 'NLU Delhi-specific strategy'] },
      { module: 'CUET-LAW Preparation', topics: ['General Test', 'Language proficiency', 'Domain subject', 'Legal awareness', 'Section-wise strategy'] },
      { module: 'MH-CET & LSAT', topics: ['Legal aptitude for MH-CET', 'Maharashtra-specific legal knowledge', 'Analytical reasoning for LSAT', 'LSAT India reading comprehension', 'Strategy for both exams'] },
      { module: 'AIL-LET & Mock Tests', topics: ['Army Institute of Law entrance', 'Legal knowledge for defence law', 'Combined mock test schedule', 'All-exam performance analysis', 'Exam-day strategy for each test'] },
    ],
    whoFor: [
      'Students targeting NLU Delhi (AILET)',
      'Students targeting Maharashtra law colleges (MH-CET)',
      'Students targeting CUET-LAW universities',
      'Students targeting LSAT India universities',
      'Students appearing in multiple law entrance exams',
    ],
    testimonial: {
      name: 'Rohan Gupta',
      rank: 'AIR 12, AILET 2024',
      college: 'NLU Delhi',
      quote: 'The OLET program covered every exam I needed. The dedicated AILET preparation was incredible — I got into NLU Delhi on my first attempt!',
      avatar: 'RG',
    },
  },

  // ── 5. Online CLAT Course ─────────────────────────────────────
  {
    slug: 'clat-online',
    title: 'Online CLAT Course',
    category: 'online',
    icon: '💻',
    color: '#08BD80',
    bg: '#E6FAF4',
    tagline: 'Live interactive online coaching — study from anywhere across India',
    overview: 'Looking for the best online CLAT coaching to ace the Common Law Admission Test (CLAT)? Join CLATians, India\'s leading CLAT preparation platform, offering live interactive classes, expert mentorship, structured study material, and real-time mock tests. Our Online CLAT Course ensures flexible learning, AI-driven performance analysis, and 24/7 access to study resources, helping you secure a seat in the top NLUs (National Law Universities) from the comfort of your home.',
    duration: '8–12 Months',
    batchSize: '50–100 Students',
    mode: 'Online (Live + Recorded)',
    fee: '₹15,000',
    emi: '₹2,500/month',
    features: [
      'Live interactive classes in Hinglish medium',
      'Recorded lectures available 24/7 on the app',
      'Digital study material + PDF notes',
      'Real-time mock tests with AI analytics',
      'Weekly live doubt-clearing sessions',
      'WhatsApp study group access',
      'Monthly progress reports',
      'Mobile app for on-the-go learning',
      'Premium features included',
      'AI-driven performance analysis dashboard',
    ],
    includes: [
      { label: 'Recorded Lectures', value: '600+ Hours', icon: '🎥' },
      { label: 'Live Classes', value: '200+ Hours', icon: '📡' },
      { label: 'Mock Tests', value: '150+ Tests', icon: '📝' },
      { label: 'Digital Notes', value: 'Complete PDFs', icon: '📄' },
      { label: 'Doubt Sessions', value: 'Weekly Live', icon: '💬' },
      { label: 'Validity', value: 'Till Exam', icon: '📅' },
    ],
    curriculum: [
      { module: 'English Language', topics: ['Video lectures on comprehension', 'Grammar rules with examples', 'Vocabulary capsules', 'Speed reading exercises', 'Sentence correction practice'] },
      { module: 'Legal Reasoning', topics: ['Concept videos with case examples', 'Legal passage-based questions', 'Practice exercises daily', 'Live application sessions', 'Judgment analysis'] },
      { module: 'Logical Reasoning', topics: ['Puzzle solving videos', 'Daily practice sets', 'Live reasoning sessions', 'Shortcut techniques', 'Critical thinking exercises'] },
      { module: 'Current Affairs & Mock Tests', topics: ['Daily news digest PDFs', 'Weekly live current affairs class', 'Monthly GK magazine', 'AI-powered mock tests', 'Performance analytics dashboard'] },
    ],
    whoFor: [
      'Students from cities without CLATians center',
      'Students who want flexibility in study timings',
      'Class 12 students juggling board exams and CLAT',
      'Students who prefer self-paced digital learning',
      'Repeat CLAT aspirants looking for affordable coaching',
    ],
    testimonial: {
      name: 'Priya Sharma',
      rank: 'AIR 47, CLAT 2024',
      college: 'NALSAR Hyderabad',
      quote: 'The online program was perfect for me. I could study at my own pace while still getting all the guidance I needed. The live sessions with faculty were extremely helpful.',
      avatar: 'PS',
    },
  },

  // ── 6. LSAT India Coaching (Online) ──────────────────────────
  {
    slug: 'lsat',
    title: 'LSAT India Coaching',
    category: 'online',
    icon: '🌍',
    color: '#08BD80',
    bg: '#E6FAF4',
    tagline: 'Crack LSAT India for Jindal Global Law School and Ashoka University',
    overview: 'LSAT India is a distinct law entrance exam that tests analytical and logical reasoning far beyond the traditional Indian law entrance pattern. CLATians\' LSAT India Coaching is designed to help you master the unique LSAT skill set — analytical reasoning, logical reasoning, and reading comprehension — needed for admission to Jindal Global Law School, Ashoka University, and other top private law colleges. Our online coaching brings expert guidance directly to you from wherever you are.',
    duration: '3–6 Months',
    batchSize: '30 Students',
    mode: 'Online (Live)',
    fee: '₹25,000',
    emi: '₹5,000/month',
    features: [
      'Comprehensive LSAT India syllabus coverage',
      'Analytical reasoning mastery — unique LSAT skill set',
      'Logical reasoning deep dives with practice sets',
      'Reading comprehension for law passages',
      'Live online sessions with LSAT expert faculty',
      '20+ full-length LSAT India mock tests',
      'Detailed performance feedback after each test',
      'Strategy sessions for Jindal Global and Ashoka admission',
    ],
    includes: [
      { label: 'Live Sessions', value: '100+ Hours', icon: '📡' },
      { label: 'Mock Tests', value: '20+ Full Tests', icon: '📝' },
      { label: 'Practice Sets', value: '500+ Questions', icon: '📋' },
      { label: 'Study Material', value: 'LSAT-specific', icon: '📖' },
      { label: 'Doubt Sessions', value: 'Weekly Live', icon: '💬' },
      { label: 'Validity', value: 'Till Exam', icon: '📅' },
    ],
    curriculum: [
      { module: 'Analytical Reasoning', topics: ['Logic games and diagram setups', 'Grouping and ordering questions', 'Constraint-based reasoning', 'Practice with timed sets', 'LSAT-specific analytical strategies'] },
      { module: 'Logical Reasoning', topics: ['Argument analysis and evaluation', 'Assumption and inference questions', 'Strengthen and weaken questions', 'Flaw identification in arguments', 'Method of reasoning questions'] },
      { module: 'Reading Comprehension', topics: ['Law-focused passage strategies', 'Multiple perspective passages', 'Comparative reading sets', 'Inference and application questions', 'Speed and accuracy techniques'] },
      { module: 'Mock Tests & Strategy', topics: ['Full-length LSAT India mocks', 'Time management for LSAT', 'Score improvement techniques', 'College-specific strategy (Jindal/Ashoka)', 'Final revision sessions'] },
    ],
    whoFor: [
      'Students targeting Jindal Global Law School (O.P. Jindal)',
      'Aspirants aiming for Ashoka University Law program',
      'Students wanting to explore top private law colleges',
      'Students who find LSAT analytical format more suitable',
      'CLAT aspirants who want additional law college options',
    ],
    testimonial: {
      name: 'Arjun Tiwari',
      rank: 'AIR 67, CLAT 2024',
      college: 'RMLNLU Lucknow',
      quote: 'LSAT prep at CLATians is excellent.',
      avatar: 'AT',
    },
  },

  // ── 7. Booster Crash Course (Online) ─────────────────────────
  {
    slug: 'booster',
    title: 'Booster Crash Course',
    category: 'online',
    icon: '⚡',
    color: '#08BD80',
    bg: '#E6FAF4',
    tagline: 'Intensive crash course for last-minute CLAT preparation — 45 days to exam day',
    overview: 'The CLATians Booster Crash Course is the ultimate last-minute preparation program for CLAT aspirants. Designed for the final 45 days before the exam, this intensive online course covers the most important topics, high-yield current affairs, rapid revision modules, and back-to-back full-length mock tests. Whether you are a student who started preparation late or someone who wants a final push, the Booster Course will sharpen your skills and boost your score in record time.',
    duration: '45 Days',
    batchSize: '100 Students',
    mode: 'Online (Live + Recorded)',
    fee: '₹8,000',
    emi: 'Full payment',
    features: [
      'Intensive 45-day program covering entire CLAT syllabus rapidly',
      'Daily live sessions covering high-yield exam topics',
      'Speed revision modules for each CLAT section',
      '10 full-length mock tests with immediate analysis',
      'Daily current affairs capsules for last-minute GK',
      'Rapid legal reasoning shortcuts and tricks',
      'Recorded sessions for flexible revision anytime',
      'WhatsApp group with doubt-clearing support',
    ],
    includes: [
      { label: 'Live Sessions', value: '45 Daily', icon: '📡' },
      { label: 'Mock Tests', value: '10+ Full Tests', icon: '📝' },
      { label: 'CA Capsules', value: 'Daily Updates', icon: '📰' },
      { label: 'Recorded Access', value: '45 Days', icon: '🎥' },
      { label: 'Study Material', value: 'Rapid Revision', icon: '📖' },
      { label: 'Support', value: 'WhatsApp Group', icon: '💬' },
    ],
    curriculum: [
      { module: 'Rapid English Revision', topics: ['High-frequency comprehension patterns', 'Grammar quick rules', 'Vocabulary shortlists for CLAT', 'Sentence correction speed drills', 'Reading speed enhancement'] },
      { module: 'Legal Reasoning Sprint', topics: ['Most important legal principles', 'Pattern-based legal passage solving', 'Rapid case law awareness', 'Application shortcuts for legal MCQs', 'High-yield legal reasoning questions'] },
      { module: 'Current Affairs Blitz', topics: ['45-day current affairs recap', 'Important legal judgments', 'National and international GK', 'Static GK rapid revision', 'Expected CA questions for CLAT'] },
      { module: 'Mock Tests & Final Strategy', topics: ['10 full-length timed mock tests', 'Post-test analysis sessions', 'Exam-day tips and strategy', 'Stress management for exam week', 'Final revision checklist'] },
    ],
    whoFor: [
      'Students in the last 45 days of CLAT preparation',
      'Aspirants who started late and need rapid coverage',
      'Students already enrolled in coaching who want an extra boost',
      'Repeat CLAT aspirants targeting score improvement',
      'Students wanting intensive focused practice before exam day',
    ],
    testimonial: {
      name: 'Vikram Mishra',
      rank: 'AIR 156, CLAT 2024',
      college: 'GNLU Gandhinagar',
      quote: 'The booster course in final 45 days was a game changer.',
      avatar: 'VM',
    },
  },

  // ── 8. Mock Test Series ───────────────────────────────────────
  {
    slug: 'mock-tests',
    title: 'Mock Test Series',
    category: 'mock',
    icon: '📝',
    color: '#08BD80',
    bg: '#E6FAF4',
    tagline: 'India\'s most comprehensive CLAT mock test series with AI analytics',
    overview: 'Practice with our comprehensive mock tests designed to simulate the actual CLAT exam experience and improve your performance. CLATians offers both offline (printable PDF) and online mock test series for CLAT 2026, with detailed solutions, performance analytics, and national rank predictions. Choose from our 10, 20, or 40 mock test bundles based on your preparation level.',
    duration: 'Access till exam',
    batchSize: 'Unlimited',
    mode: 'Online (Self-paced)',
    fee: '₹2,999',
    emi: 'Full payment',
    features: [
      'CLAT Mock Test Series — 10, 20 or 40 Full Mocks',
      'Printable PDF format for offline practice anywhere',
      'Detailed solutions and explanations for every question',
      'No internet required for PDF tests',
      'Perfect for simulating actual CLAT exam conditions',
      'Comprehensive answer keys included',
      'Free performance report after every test',
      'Monthly GK & Legal Current Affairs updates',
      'Sectional performance analytics',
      'AI-powered performance tracking (40 Mock bundle)',
    ],
    includes: [
      { label: 'Full Mock Tests', value: 'Up to 40', icon: '📋' },
      { label: 'Sectional Tests', value: '200+', icon: '📊' },
      { label: 'Previous Papers', value: '10 Years', icon: '📅' },
      { label: 'Answer Keys', value: 'All Tests', icon: '✅' },
      { label: 'PDF Downloads', value: 'Unlimited', icon: '📥' },
      { label: 'Validity', value: 'Till Exam', icon: '🗓️' },
    ],
    curriculum: [
      { module: 'CLAT Mock Test Series — 10 Mocks', topics: ['10 full-length mocks based on latest CLAT pattern', 'Detailed solutions & explanations', 'Free performance report after every test', 'Ideal for early self-assessment', 'Beginner level — Easy difficulty'] },
      { module: 'CLAT Mock Test Series — 20 Mocks', topics: ['20 expertly designed mocks covering all CLAT sections', 'Monthly GK & Legal Current Affairs updates', 'Sectional performance analytics', 'Best for intermediate preparation', 'Medium difficulty level'] },
      { module: 'CLAT Mock Test Series — 40 Mocks', topics: ['40 full-length mocks for ultimate CLAT readiness', 'AI-powered performance tracking', 'All India Ranking & leaderboard', 'Free final revision tests', 'Access to exclusive topper strategy sessions'] },
      { module: 'Sectional Practice', topics: ['English Language tests', 'Legal Reasoning tests', 'Logical Reasoning tests', 'Current Affairs & GK tests', 'Quantitative Techniques tests'] },
    ],
    whoFor: [
      'Students already enrolled in offline or online coaching',
      'Self-study students who need structured test practice',
      'Students in the final 3–6 months of CLAT preparation',
      'Students wanting to check exam readiness and rank',
      'Repeat CLAT aspirants improving scores from last year',
    ],
    testimonial: {
      name: 'Sneha Patel',
      rank: 'AIR 89, CLAT 2024',
      college: 'NLIU Bhopal',
      quote: 'The CLATians mock tests were exactly like the real exam. The detailed solutions helped me understand where I was going wrong and fix it before the actual exam.',
      avatar: 'SP',
    },
  },

  // ── MENTORSHIP ────────────────────────────────────────────────
  {
    slug: 'mentorship-clat',
    title: 'CLAT Mentorship',
    category: 'mentorship',
    icon: '🎯',
    color: '#08BD80',
    bg: '#E6FAF4',
    tagline: '1-on-1 personalized guidance from NLU toppers for CLAT preparation',
    overview: 'Get personalized 1-on-1 mentorship from NLU toppers and experienced legal professionals who have cracked CLAT themselves. Our CLAT Mentorship program provides customized study plans, targeted doubt resolution, and strategic guidance tailored to your strengths and weaknesses. Unlike classroom coaching, every session is focused entirely on YOU.',
    duration: '1–6 Months',
    batchSize: '1 Student (1-on-1)',
    mode: 'Online (WhatsApp + Video Call)',
    fee: '₹5,000',
    emi: 'One-time payment',
    features: [
      '1-on-1 sessions with NLU topper mentor',
      'Customized study plan based on your strengths',
      'Daily/weekly WhatsApp check-ins',
      'Mock test review and analysis',
      'Interview and GD preparation',
      'College selection and counselling guidance',
    ],
    includes: [
      { label: 'Sessions', value: '4–Unlimited', icon: '🎯' },
      { label: 'Study Plan', value: 'Custom', icon: '📋' },
      { label: 'WhatsApp', value: 'Direct Access', icon: '💬' },
      { label: 'Mock Review', value: 'Included', icon: '📝' },
    ],
    curriculum: [
      { module: 'Assessment & Planning', topics: ['Initial performance assessment', 'Weak area identification', 'Custom study schedule', 'Goal setting'] },
      { module: 'Subject-wise Guidance', topics: ['English & comprehension strategy', 'Legal reasoning approach', 'Current affairs planning', 'Quantitative techniques'] },
      { module: 'Test Strategy', topics: ['Mock test review sessions', 'Time management techniques', 'Attempt strategy', 'Score improvement plan'] },
    ],
    whoFor: [
      'Students who want personalized 1-on-1 attention',
      'Repeaters looking to improve their CLAT score',
      'Students with busy schedules needing flexible guidance',
      'Students wanting NLU topper perspective and strategy',
    ],
    testimonial: {
      name: 'Vikram Nair',
      rank: 'AIR 23, CLAT 2024',
      college: 'NLSIU Bangalore',
      quote: 'The 1-on-1 mentorship was a game changer. My mentor knew exactly where I was weak and helped me fix those areas systematically. Cleared in one attempt!',
      avatar: 'VN',
    },
  },
  {
    slug: 'mentorship-ailet',
    title: 'AILET Mentorship',
    category: 'mentorship',
    icon: '⚖️',
    color: '#6d28d9',
    bg: '#EDE9FE',
    tagline: '1-on-1 focused guidance for AILET — NLU Delhi specific preparation',
    overview: 'AILET has a distinct pattern compared to CLAT. Our AILET-specific mentorship program provides focused 1-on-1 guidance for NLU Delhi admission. Get expert advice on AILET-specific sections including General Knowledge, Elementary Mathematics, and English — all from mentors who have cracked AILET themselves.',
    duration: '1–4 Months',
    batchSize: '1 Student (1-on-1)',
    mode: 'Online (WhatsApp + Video Call)',
    fee: '₹6,000',
    emi: 'One-time payment',
    features: [
      'AILET-specific preparation strategy',
      'GK & current affairs for AILET pattern',
      'Elementary mathematics guidance',
      '1-on-1 sessions with AILET cleared mentor',
      'NLU Delhi specific interview preparation',
      'Custom study plan for AILET timeline',
    ],
    includes: [
      { label: 'Sessions', value: '4–Unlimited', icon: '🎯' },
      { label: 'GK Updates', value: 'Daily', icon: '📰' },
      { label: 'Study Plan', value: 'AILET-specific', icon: '📋' },
      { label: 'Mock Review', value: 'Included', icon: '📝' },
    ],
    curriculum: [
      { module: 'AILET Pattern Mastery', topics: ['English language for AILET', 'General knowledge strategy', 'Elementary mathematics', 'Legal aptitude approach'] },
      { module: 'Mock & Analysis', topics: ['AILET mock test review', 'Score improvement plan', 'Time management for AILET', 'Attempt sequence strategy'] },
    ],
    whoFor: [
      'Students specifically targeting NLU Delhi (AILET)',
      'Students strong in CLAT but weak in AILET-specific sections',
      'Students wanting focused NLU Delhi preparation',
    ],
    testimonial: {
      name: 'Ananya Verma',
      rank: 'AIR 12, AILET 2024',
      college: 'NLU Delhi',
      quote: 'The AILET-specific mentorship helped me understand the pattern differences from CLAT. The GK strategy sessions were incredibly valuable.',
      avatar: 'AV',
    },
  },
  {
    slug: 'mentorship-nlu-counselling',
    title: 'NLU Counselling',
    category: 'mentorship',
    icon: '🏛️',
    color: '#1d4ed8',
    bg: '#DBEAFE',
    tagline: 'Post-result NLU counselling — college selection, allotment & admission guidance',
    overview: 'After CLAT results, the counselling round is the most crucial step. Our NLU Counselling program guides you through the entire process — from preference filling strategy to understanding cut-offs, seat allotment, and document verification. Our mentors have helped 500+ students secure their preferred NLUs through strategic counselling.',
    duration: '2–4 Weeks',
    batchSize: '1 Student (1-on-1)',
    mode: 'Online (WhatsApp + Video Call)',
    fee: '₹3,000',
    emi: 'One-time payment',
    features: [
      'NLU preference order strategy',
      'Cut-off analysis and prediction',
      'Document checklist and verification help',
      'Round-wise seat allotment guidance',
      'Withdrawal and upgrade strategy',
      '500+ students counselled successfully',
    ],
    includes: [
      { label: 'Sessions', value: '2–4 Sessions', icon: '🎯' },
      { label: 'Cut-off Data', value: 'All NLUs', icon: '📊' },
      { label: 'Support', value: 'Till Admission', icon: '✅' },
      { label: 'Preference Help', value: 'Included', icon: '🏛️' },
    ],
    curriculum: [
      { module: 'Pre-Counselling', topics: ['Score-based NLU shortlisting', 'Cut-off analysis', 'Preference order strategy', 'Category-wise guidance'] },
      { module: 'During Counselling', topics: ['Round-wise allotment tracking', 'Upgrade/freeze/withdrawal decisions', 'Document preparation', 'Fee payment guidance'] },
    ],
    whoFor: [
      'Students who have appeared in CLAT/AILET and awaiting results',
      'Students confused about NLU preference order',
      'Students wanting data-driven college selection guidance',
    ],
    testimonial: {
      name: 'Rahul Mehta',
      rank: 'AIR 67, CLAT 2024',
      college: 'NLIU Bhopal',
      quote: 'Without the counselling guidance I would have made wrong preference choices. The cut-off data and upgrade strategy helped me get NLIU Bhopal in round 2.',
      avatar: 'RM',
    },
  },
];

export function getCourseBySlug(slug: string): Course | undefined {
  return courses.find((c) => c.slug === slug);
}
